выполнены задачи 8 модуля
js-tasks-ru/jsbasic-20240422_ildarado12 pull request #12
Opened 2024-06-23 07:29 UTC by ildarado12

2024-06-23 07:30 UTC, jsru-1 commented
Проверьте, пожалуйста, ваше решение, не все тесты прошли (PR не будет принят до тех пор, пока **все** добавленные задачи не будут решены).

2024-06-26 04:22 UTC, koalex requested changes
Скинул в Discord замечания по **8-1**

2024-06-26 16:24 UTC, jsru-1 commented
Добавляю преподавателя (@koalex) для код-ревью.

2024-06-27 10:54 UTC, koalex approved these changes

2024-06-27 10:55 UTC, merged