Функция для вычисления факториала.
js-tasks-ru/jsbasic-20240422_ildarado12 pull request #2
Opened 2024-04-25 21:03 UTC by ildarado12

2024-04-25 21:03 UTC, jsru-1 commented
Добавляю преподавателя (@koalex) для код-ревью.

2024-04-26 03:42 UTC, koalex requested changes
Исправить замечание в **1-1**

2024-04-26 03:42 UTC, koalex commented on 1-module/1-task/index.js
> +alert(factorial(1));
`alert` нужно удалить, он будет потом мешать тестам

2024-04-26 17:56 UTC, jsru-1 commented
Добавляю преподавателя (@koalex) для код-ревью.

2024-04-27 05:05 UTC, koalex requested changes
Исправить замечание

2024-04-27 05:05 UTC, koalex commented on 1-module/1-task/index.js
> +    alert(`Введите положительное число или ноль.`);
Удалить `alert`. Он может помешать автотестам.

2024-04-27 12:49 UTC, jsru-1 commented
Добавляю преподавателя (@koalex) для код-ревью.

2024-04-28 11:07 UTC, jsru-1 commented
Решение было обновлено, посмотрим что скажет @koalex

2024-04-28 12:43 UTC, koalex approved these changes

2024-04-28 12:43 UTC, koalex commented on 1-module/4-task/index.js
> +  if (str.includes(`xxx`) || str.includes(`1xbet`)) {
Можно сразу так:
`return str.includes(`xxx`) || str.includes(`1xbet`);`

2024-04-28 12:43 UTC, merged