Выполнены задачи в 3м модуле, не проходит тест 3 задача
js-tasks-ru/jsbasic-20240422_ildarado12 pull request #5
Opened 2024-05-04 17:10 UTC by ildarado12

2024-05-04 17:11 UTC, jsru-1 commented
Проверьте, пожалуйста, ваше решение, не все тесты прошли (PR не будет принят до тех пор, пока **все** добавленные задачи не будут решены).

2024-05-05 09:46 UTC, koalex requested changes
Опечатка в **3-3**

2024-05-05 09:46 UTC, koalex commented on 3-module/3-task/index.js
> +  let arrPropCamel = property.split(`-`).map((word, index) => {
Опечатка. Надо `str.split(`-`)`

2024-05-05 10:14 UTC, ildarado12 commented on 3-module/3-task/index.js
> +  let arrPropCamel = property.split(`-`).map((word, index) => {
Спасибо, исправил.

2024-05-05 10:15 UTC, jsru-1 commented
Добавляю преподавателя (@koalex) для код-ревью.

2024-05-05 10:16 UTC, koalex approved these changes

2024-05-05 10:17 UTC, merged